# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interstellar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interstellar.proto',
  package='interstellar',
  syntax='proto3',
  serialized_pb=_b('\n\x12interstellar.proto\x12\x0cinterstellar\"(\n\x0cHelloRequest\x12\x18\n\x10hello_from_earth\x18\x01 \x01(\t\"(\n\rHelloResponse\x12\x17\n\x0fhello_from_mars\x18\x01 \x01(\t\"!\n\x0eMessageRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\")\n\x16StreamMessageFromEarth\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\rReplyFromMars\x12\r\n\x05reply\x18\x01 \x01(\t\"(\n\x15StreamMessageFromMars\x12\x0f\n\x07message\x18\x01 \x01(\t2\x88\x03\n\x19InterstellarCommunication\x12\x45\n\x08SayHello\x12\x1a.interstellar.HelloRequest\x1a\x1b.interstellar.HelloResponse\"\x00\x12[\n\x12GetMessageFromMars\x12\x1c.interstellar.MessageRequest\x1a#.interstellar.StreamMessageFromMars\"\x00\x30\x01\x12]\n\x14SendMessageFromEarth\x12$.interstellar.StreamMessageFromEarth\x1a\x1b.interstellar.ReplyFromMars\"\x00(\x01\x12h\n\x15SendAndReceiveMessage\x12$.interstellar.StreamMessageFromEarth\x1a#.interstellar.StreamMessageFromMars\"\x00(\x01\x30\x01\x62\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='interstellar.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hello_from_earth', full_name='interstellar.HelloRequest.hello_from_earth', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=76,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='interstellar.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hello_from_mars', full_name='interstellar.HelloResponse.hello_from_mars', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=118,
)


_MESSAGEREQUEST = _descriptor.Descriptor(
  name='MessageRequest',
  full_name='interstellar.MessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='interstellar.MessageRequest.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=153,
)


_STREAMMESSAGEFROMEARTH = _descriptor.Descriptor(
  name='StreamMessageFromEarth',
  full_name='interstellar.StreamMessageFromEarth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='interstellar.StreamMessageFromEarth.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=196,
)


_REPLYFROMMARS = _descriptor.Descriptor(
  name='ReplyFromMars',
  full_name='interstellar.ReplyFromMars',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='interstellar.ReplyFromMars.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=228,
)


_STREAMMESSAGEFROMMARS = _descriptor.Descriptor(
  name='StreamMessageFromMars',
  full_name='interstellar.StreamMessageFromMars',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='interstellar.StreamMessageFromMars.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=270,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE
DESCRIPTOR.message_types_by_name['MessageRequest'] = _MESSAGEREQUEST
DESCRIPTOR.message_types_by_name['StreamMessageFromEarth'] = _STREAMMESSAGEFROMEARTH
DESCRIPTOR.message_types_by_name['ReplyFromMars'] = _REPLYFROMMARS
DESCRIPTOR.message_types_by_name['StreamMessageFromMars'] = _STREAMMESSAGEFROMMARS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'interstellar_pb2'
  # @@protoc_insertion_point(class_scope:interstellar.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLORESPONSE,
  __module__ = 'interstellar_pb2'
  # @@protoc_insertion_point(class_scope:interstellar.HelloResponse)
  ))
_sym_db.RegisterMessage(HelloResponse)

MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEREQUEST,
  __module__ = 'interstellar_pb2'
  # @@protoc_insertion_point(class_scope:interstellar.MessageRequest)
  ))
_sym_db.RegisterMessage(MessageRequest)

StreamMessageFromEarth = _reflection.GeneratedProtocolMessageType('StreamMessageFromEarth', (_message.Message,), dict(
  DESCRIPTOR = _STREAMMESSAGEFROMEARTH,
  __module__ = 'interstellar_pb2'
  # @@protoc_insertion_point(class_scope:interstellar.StreamMessageFromEarth)
  ))
_sym_db.RegisterMessage(StreamMessageFromEarth)

ReplyFromMars = _reflection.GeneratedProtocolMessageType('ReplyFromMars', (_message.Message,), dict(
  DESCRIPTOR = _REPLYFROMMARS,
  __module__ = 'interstellar_pb2'
  # @@protoc_insertion_point(class_scope:interstellar.ReplyFromMars)
  ))
_sym_db.RegisterMessage(ReplyFromMars)

StreamMessageFromMars = _reflection.GeneratedProtocolMessageType('StreamMessageFromMars', (_message.Message,), dict(
  DESCRIPTOR = _STREAMMESSAGEFROMMARS,
  __module__ = 'interstellar_pb2'
  # @@protoc_insertion_point(class_scope:interstellar.StreamMessageFromMars)
  ))
_sym_db.RegisterMessage(StreamMessageFromMars)



_INTERSTELLARCOMMUNICATION = _descriptor.ServiceDescriptor(
  name='InterstellarCommunication',
  full_name='interstellar.InterstellarCommunication',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=273,
  serialized_end=665,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='interstellar.InterstellarCommunication.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMessageFromMars',
    full_name='interstellar.InterstellarCommunication.GetMessageFromMars',
    index=1,
    containing_service=None,
    input_type=_MESSAGEREQUEST,
    output_type=_STREAMMESSAGEFROMMARS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendMessageFromEarth',
    full_name='interstellar.InterstellarCommunication.SendMessageFromEarth',
    index=2,
    containing_service=None,
    input_type=_STREAMMESSAGEFROMEARTH,
    output_type=_REPLYFROMMARS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendAndReceiveMessage',
    full_name='interstellar.InterstellarCommunication.SendAndReceiveMessage',
    index=3,
    containing_service=None,
    input_type=_STREAMMESSAGEFROMEARTH,
    output_type=_STREAMMESSAGEFROMMARS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTERSTELLARCOMMUNICATION)

DESCRIPTOR.services_by_name['InterstellarCommunication'] = _INTERSTELLARCOMMUNICATION

# @@protoc_insertion_point(module_scope)
